#cloud-config
package_upgrade: true
packages:
  - net-tools
  - nginx
  - jq

runcmd:
  - echo "net.ipv6.conf.all.disable_ipv6=1" | sudo tee -a /etc/sysctl.conf
  - echo "net.ipv6.conf.default.disable_ipv6=1" | sudo tee -a /etc/sysctl.conf
  - echo "net.ipv6.conf.lo.disable_ipv6=1" | sudo tee -a /etc/sysctl.conf
  - wget https://github.com/etcd-io/etcd/releases/download/v3.5.6/etcd-v3.5.6-linux-arm64.tar.gz
  - tar -xvf etcd-v3.5.6-linux-arm64.tar.gz
  - sudo mv etcd-v3.5.6-linux-arm64/etcd* /usr/local/bin/
  - sudo mkdir -p /etc/etcd /var/lib/etcd
  - sudo chmod 700 /var/lib/etcd
  - wget https://dl.k8s.io/v1.26.0/bin/linux/arm64/kubectl
  - wget https://dl.k8s.io/v1.26.0/bin/linux/arm64/kube-apiserver
  - wget https://dl.k8s.io/v1.26.0/bin/linux/arm64/kube-controller-manager
  - wget https://dl.k8s.io/v1.26.0/bin/linux/arm64/kube-scheduler
  - chmod +x kube-apiserver kube-controller-manager kube-scheduler kubectl
  - sudo mv kube-apiserver kube-controller-manager kube-scheduler kubectl /usr/local/bin/
  - [kubectl, version, --client]
  - sudo mkdir -p /etc/kubernetes/config /var/lib/kubernetes/
