# https://kubernetes.io/docs/reference/config-api/kube-scheduler-config.v1/
apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: true
clientConnection:
  kubeconfig: "/var/lib/kubernetes/kube-scheduler.kubeconfig"