#cloud-config
package_upgrade: true
packages:
  - net-tools
  - nginx
  - jq

runcmd:
#  - curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
  - wget https://github.com/etcd-io/etcd/releases/download/v3.5.6/etcd-v3.5.6-linux-amd64.tar.gz
  - tar -xvf etcd-v3.5.6-linux-amd64.tar.gz
  - sudo mv etcd-v3.5.6-linux-amd64/etcd* /usr/local/bin/
  - sudo mkdir -p /etc/etcd /var/lib/etcd
  - sudo chmod 700 /var/lib/etcd
  - wget https://dl.k8s.io/v1.26.0/bin/linux/amd64/kubectl
  - [wget, https://dl.k8s.io/v1.26.0/bin/linux/amd64/kube-apiserver]
  - [wget, https://dl.k8s.io/v1.26.0/bin/linux/amd64/kube-controller-manager]
  - [wget, https://dl.k8s.io/v1.26.0/bin/linux/amd64/kube-scheduler]
  - chmod +x kube-apiserver kube-controller-manager kube-scheduler kubectl
  - sudo mv kube-apiserver kube-controller-manager kube-scheduler kubectl /usr/local/bin/
  - [kubectl, version, --client]
  - sudo mkdir -p /etc/kubernetes/config /var/lib/kubernetes/
