#cloud-config
package_upgrade: true
packages:
  - net-tools
  - socat
  - conntrack
  - ipset
  - jq

runcmd:
  - echo "net.ipv4.conf.all.forwarding=1" | sudo tee -a /etc/sysctl.conf
  - sudo swapoff -a
  - wget https://dl.k8s.io/v1.26.0/bin/linux/amd64/kubectl
  - [wget, https://dl.k8s.io/v1.26.0/bin/linux/amd64/kube-proxy]
  - wget https://dl.k8s.io/v1.26.0/bin/linux/amd64/kubelet
  - wget https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.26.0/crictl-v1.26.0-linux-amd64.tar.gz
  - wget https://github.com/opencontainers/runc/releases/download/v1.1.9/runc.amd64
  - wget https://github.com/containernetworking/plugins/releases/download/v1.1.0/cni-plugins-linux-amd64-v1.1.0.tgz
  - wget https://github.com/containerd/containerd/releases/download/v1.6.4/containerd-1.6.4-linux-amd64.tar.gz
  - sudo mkdir -p /etc/cni/net.d /opt/cni/bin /var/lib/kubelet /var/lib/kube-proxy /var/lib/kubernetes /var/run/kubernetes
  - sudo mkdir -p /etc/containerd/
  - mkdir containerd
  - tar -xvf crictl-v1.26.0-linux-amd64.tar.gz
  - tar -xvf containerd-1.6.4-linux-amd64.tar.gz -C containerd
  - sudo tar -xvf cni-plugins-linux-amd64-v1.1.0.tgz -C /opt/cni/bin/
  - sudo mv runc.amd64 runc
  - chmod +x crictl kubectl kube-proxy kubelet runc
  - sudo mv crictl kubectl kube-proxy kubelet runc /usr/local/bin/
  - sudo mv containerd/bin/* /bin/