#cloud-config
package_upgrade: true
packages:
  - net-tools
  - socat
  - conntrack
  - ipset
  - jq

runcmd:
  - echo "net.ipv4.conf.all.forwarding=1" | sudo tee -a /etc/sysctl.conf
  - sudo swapoff -a
  - wget https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.26.0/crictl-v1.26.0-linux-arm64.tar.gz
  - wget https://github.com/opencontainers/runc/releases/download/v1.1.9/runc.arm64
  - wget https://github.com/containernetworking/plugins/releases/download/v1.1.0/cni-plugins-linux-arm64-v1.1.0.tgz
  - wget https://github.com/containerd/containerd/releases/download/v1.6.4/containerd-1.6.4-linux-arm64.tar.gz
  - sudo mkdir -p /etc/containerd/ /etc/cni/net.d /opt/cni/bin
  - mkdir containerd
  - tar -xvf crictl-v1.26.0-linux-arm64.tar.gz
  - tar -xvf containerd-1.6.4-linux-arm64.tar.gz -C containerd
  - sudo tar -xvf cni-plugins-linux-arm64-v1.1.0.tgz -C /opt/cni/bin/
  - sudo mv runc.arm64 runc
  - chmod +x crictl runc
  - sudo mv crictl runc /usr/local/bin/
  - sudo mv containerd/bin/* /bin/
  - wget https://dl.k8s.io/v1.26.0/bin/linux/arm64/kubectl
  - wget https://dl.k8s.io/v1.26.0/bin/linux/arm64/kube-proxy
  - wget https://dl.k8s.io/v1.26.0/bin/linux/arm64/kubelet
  - sudo mkdir -p /var/lib/kubelet /var/lib/kube-proxy /var/lib/kubernetes /var/run/kubernetes
  - chmod +x kubectl kube-proxy kubelet
  - sudo mv kubectl kube-proxy kubelet /usr/local/bin/
